import { expect, test } from 'bun:test'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parse } from 'smol-toml'
import { runCliProgram } from '../src/cli/program'
import { bundledCodexCatalogBoundary, DISCOVERY, setupProgramHome } from './cli-program-test-support'

let home = ''
setupProgramHome('codex-launch-refresh-', (path) => { home = path })

test('each Codex launch replaces revoked models before spawning and preserves other settings', async () => {
  let models = [{ id: 'gpt-6-astra' }, { id: 'retired-model' }]
  let requests = 0
  const server = Bun.serve({ port: 0, fetch(request) {
    if (new URL(request.url).pathname === '/v1/models') {
      requests += 1
      expect(request.headers.get('authorization')).toBe('Bearer runtime-key')
      return Response.json({ data: models })
    }
    return Response.json({ data: [] })
  } })
  try {
    const context = { env: { HOME: home, LITELLM_PROXY_API_KEY: 'runtime-key' }, now: () => new Date(0) }
    const installed = await runCliProgram(['install', '--target', 'codex', '--codex-mode', 'gateway',
      '--base-url', server.url.origin, '--non-interactive'], {
      ...context, gatewayDiscovery: async () => DISCOVERY, codexSpawnBoundary: bundledCodexCatalogBoundary(),
    })
    expect(installed.exitCode).toBe(0)
    const configPath = join(home, '.codex', 'config.toml')
    writeFileSync(configPath, `${readFileSync(configPath, 'utf8')}\n[notice]\nhide_rate_limit_model_nudge = true\n`)
    const snapshots: string[][] = []
    const launchContext = { ...context, codexSpawnBoundary: bundledCodexCatalogBoundary(), agentLaunchBoundary: {
      which: (command: string) => command,
      spawn: () => {
        const config = parse(readFileSync(configPath, 'utf8'))
        const catalogPath = config.model_catalog_json
        if (typeof catalogPath !== 'string') throw new Error('missing catalog path')
        const catalog = JSON.parse(readFileSync(catalogPath, 'utf8'))
        snapshots.push(catalog.models.map((model: { readonly slug: string }) => model.slug))
        return { status: 0, signal: null }
      },
    } }
    expect((await runCliProgram(['codex', 'exec', 'first'], launchContext)).exitCode).toBe(0)
    models = ['student-auto', 'gpt-5.6-luna', 'gpt-5.6-terra', 'gpt-6-astra'].map((id) => ({ id }))
    expect((await runCliProgram(['codex', 'exec', 'second'], launchContext)).exitCode).toBe(0)
    expect(requests).toBe(2)
    expect(snapshots[0]).toContain('retired-model')
    expect(snapshots[1]).not.toContain('retired-model')
    expect(snapshots[1]).toContain('student-auto')
    expect(parse(readFileSync(configPath, 'utf8')).model).toBe('gpt-6-astra')
    expect(readFileSync(configPath, 'utf8')).toContain('hide_rate_limit_model_nudge = true')
  } finally { server.stop(true) }
})

test('will not overwrite an unrelated catalog path', async () => {
  const context = { env: { HOME: home, LITELLM_PROXY_API_KEY: 'runtime-key' }, now: () => new Date(0) }
  await runCliProgram(['install', '--target', 'codex', '--codex-mode', 'gateway',
    '--base-url', 'https://example.test', '--non-interactive'], {
    ...context, gatewayDiscovery: async () => DISCOVERY, codexSpawnBoundary: bundledCodexCatalogBoundary(),
  })
  const configPath = join(home, '.codex', 'config.toml')
  const unrelated = join(home, 'unrelated.json')
  writeFileSync(unrelated, 'keep this')
  writeFileSync(configPath, readFileSync(configPath, 'utf8').replace(
    /^model_catalog_json = .*$/m, `model_catalog_json = ${JSON.stringify(unrelated)}`,
  ))
  let spawned = false
  const result = await runCliProgram(['codex', 'exec', 'test'], { ...context,
    agentLaunchBoundary: { which: (command) => command, spawn: () => {
      spawned = true
      return { status: 0, signal: null }
    } },
  })
  expect(result.exitCode).toBe(1)
  expect(spawned).toBe(false)
  expect(readFileSync(unrelated, 'utf8')).toBe('keep this')
})

test('refresh replaces cached native capabilities after a Codex upgrade', async () => {
  // Given: an installed catalog generated by an older native Codex
  const server = Bun.serve({ port: 0, fetch() { return Response.json({ data: [{ id: 'coding-fast' }] }) } })
  try {
    const context = { env: { HOME: home, LITELLM_PROXY_API_KEY: 'runtime-key' }, now: () => new Date(0) }
    const installed = await runCliProgram(['install', '--target', 'codex', '--codex-mode', 'gateway',
      '--base-url', server.url.origin, '--non-interactive'], {
      ...context, gatewayDiscovery: async () => DISCOVERY, codexSpawnBoundary: bundledCodexCatalogBoundary(),
    })
    expect(installed.exitCode).toBe(0)
    const native = bundledCodexCatalogBoundary().spawn('codex', [])
    if (typeof native.stdout !== 'string') throw new Error('missing native fixture')
    const catalog = JSON.parse(native.stdout)
    catalog.models[0].comp_hash = 'upgraded-codex-machine-hash'
    let spawnedHash: unknown

    // When: the next launch discovers the same gateway model with an updated native CLI
    const result = await runCliProgram(['codex', 'exec', 'fixture'], {
      ...context,
      codexSpawnBoundary: { spawn: () => ({ status: 0, stdout: JSON.stringify(catalog) }) },
      agentLaunchBoundary: { which: (command) => command, spawn: () => {
        const config = parse(readFileSync(join(home, '.codex', 'config.toml'), 'utf8'))
        if (typeof config.model_catalog_json !== 'string') throw new Error('missing managed catalog')
        spawnedHash = JSON.parse(readFileSync(config.model_catalog_json, 'utf8')).models[0].comp_hash
        return { status: 0, signal: null }
      } },
    })

    // Then: the child sees the currently installed native capability template
    expect(result.exitCode).toBe(0)
    expect(spawnedHash).toBe('upgraded-codex-machine-hash')
  } finally { server.stop(true) }
})

test('does not launch with cached permissions when a changed credential cannot refresh', async () => {
  // Given: a cached catalog from a different credential and an unavailable gateway
  const server = Bun.serve({ port: 0, fetch() { return new Response('unavailable', { status: 503 }) } })
  try {
    const context = { env: { HOME: home, LITELLM_PROXY_API_KEY: 'old-key' }, now: () => new Date(0) }
    const installed = await runCliProgram(['install', '--target', 'codex', '--codex-mode', 'gateway',
      '--base-url', server.url.origin, '--non-interactive'], {
      ...context, gatewayDiscovery: async () => DISCOVERY, codexSpawnBoundary: bundledCodexCatalogBoundary(),
    })
    expect(installed.exitCode).toBe(0)
    let spawned = false

    // When: a different credential attempts to launch while permissions cannot be verified
    const result = await runCliProgram(['codex', 'exec', 'fixture'], {
      ...context, env: { HOME: home, LITELLM_PROXY_API_KEY: 'new-key' },
      codexSpawnBoundary: bundledCodexCatalogBoundary(),
      agentLaunchBoundary: { which: (command) => command, spawn: () => {
        spawned = true
        return { status: 0, signal: null }
      } },
    })

    // Then: an unbound catalog cannot restore the previous credential's permissions
    expect(result.exitCode).toBe(1)
    expect(spawned).toBe(false)
  } finally { server.stop(true) }
})
